# This file was generated by GoReleaser. DO NOT EDIT.
cask "cops" do
  name "cops"
  desc "The deterministic package manager for your GitHub Copilot agent files"
  homepage "https://github.com/cbout22/copilot-sync"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cops"

  on_macos do
    on_intel do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_darwin_amd64.tar.gz"
      sha256 "9156ae03e2e1135ce6b819d919ddaf29887090b29fdb821a199b0e26447deaeb"
    end
    on_arm do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_darwin_arm64.tar.gz"
      sha256 "1650291085eea5fcaf36c7c9a49bd183b61c8b6e11a07cb7c959302df2b6dddd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_linux_amd64.tar.gz"
      sha256 "44d9aca8d43474d505090c7b60576db5bcd6f74bb08091309a2120604810861d"
    end
    on_arm do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_linux_arm64.tar.gz"
      sha256 "e71004058419990da780d990079e633674868db860dc562ea356a75dace59953"
    end
  end

  # No zap stanza required
end
