# This file was generated by GoReleaser. DO NOT EDIT.
cask "cops" do
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_darwin_amd64.tar.gz"
      sha256 "83d8c9dc2c5ca85b234c5e87164df71042790e964c060de36a8fe214004c2f48"
    end
    on_arm do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_darwin_arm64.tar.gz"
      sha256 "3c469677f7c12472cda0d93cc0a69a579192a058176b8f6bdd5eb6a43be4b9b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_linux_amd64.tar.gz"
      sha256 "2053a9d5e3695a8295ef9ae27a539a7888597184beffa0288490145d0cf04dbb"
    end
    on_arm do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_linux_arm64.tar.gz"
      sha256 "493b288358e420d5c5ce8bc4e2185f46428e9bed77c97873f44862a32145d60e"
    end
  end

  name "cops"
  desc "The deterministic package manager for your GitHub Copilot agent files"
  homepage "https://github.com/cbout22/copilot-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cops"]
    end
  end

  # No zap stanza required

end
