# This file was generated by GoReleaser. DO NOT EDIT.
cask "cops" do
  name "cops"
  desc "The deterministic package manager for your GitHub Copilot agent files"
  homepage "https://github.com/cbout22/copilot-sync"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cops"

  on_macos do
    on_intel do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_darwin_amd64.tar.gz"
      sha256 "dc03251ed2b2e702170419438ab7c47df51c2930929fc47d3f513c06b984591b"
    end
    on_arm do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_darwin_arm64.tar.gz"
      sha256 "896e0bd4641bbbb474a3fd603ace1181e110cab26c91afb3a3fba637b878ceda"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_linux_amd64.tar.gz"
      sha256 "bd3442cdfa2b9abc2284cc3a39939a7457ed903792ba97e3daa320c379943809"
    end
    on_arm do
      url "https://github.com/cbout22/copilot-sync/releases/download/v#{version}/cops_#{version}_linux_arm64.tar.gz"
      sha256 "df26c04ff73b225af91a73173ce45cfb8250b1eff01a1b5dba9b08d2b1006986"
    end
  end

  # No zap stanza required
end
